project:
  type: website
  output-dir: docs

website:
  title: "SISSA Practical Statistics in R"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Lectures"
        menu:
          - practicals/Step1_pca.qmd
          - practicals/Step2_distributions.qmd
          - practicals/Step3_hypothesis_testing.qmd
          - practicals/Step4_regression.qmd
          - practicals/Step5_mixed_effects.qmd

format:
  html:
    theme: cosmo
    toc: true